More robust CI

diff --git a/.github/workflows/build-flavor.yaml b/.github/workflows/build-flavor.yaml
--- a/.github/workflows/build-flavor.yaml
+++ b/.github/workflows/build-flavor.yaml
@@ -3,12 +3,19 @@ name: Build Flavor
 on:
   workflow_call:
     inputs:
+      only-validate:
+        required: true
+        type: boolean
       kotlin-version:
         required: true
         type: string
       base-image:
         required: true
         type: string
+      platforms:
+        required: false
+        type: string
+        default: '["linux/amd64", "linux/arm64"]'
       latest:
         required: false
         type: boolean
@@ -19,13 +26,12 @@ env:
 
 jobs:
   build:
+    name: Build image
     runs-on: ubuntu-latest
     strategy:
-      fail-fast: false
+      fail-fast: ${{ inputs.only-validate }}
       matrix:
-        platform:
-          - linux/amd64
-          - linux/arm64
+        platform: ${{ fromJSON(inputs.platforms) }}
     outputs:
       digest-prefix: ${{ env.TAG_PREFIX_DIGEST }}
     steps:
@@ -38,6 +44,10 @@ jobs:
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+        with:
+          buildkitd-config-inline: |
+            [registry."docker.io"]
+              mirrors = ["mirror.gcr.io"]
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -48,11 +58,23 @@ jobs:
         uses: docker/build-push-action@v6
         with:
           platforms: ${{ matrix.platform }}
+          load: true
           build-args: |
             KOTLIN_VERSION=${{ inputs.kotlin-version }}
             BASE_IMAGE=${{ inputs.base-image }}
           labels: ${{ steps.meta.outputs.labels }}
           outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
+      - name: Test image
+        shell: bash
+        run: |
+          mkdir -p ./scripts/
+          echo 'java.io.File("/scripts/test.ok").writeText("OK")' > "./scripts/test.kts"
+          docker run --rm -v "./scripts/:/scripts/" ${{ steps.build.outputs.imageid }} /scripts/test.kts
+          
+          if [ ! -f ./scripts/test.ok ]; then 
+            echo "::error::Failed to run Kotlin script inside container failed"
+            exit 1
+          fi
       - name: Export digest
         run: |
           mkdir -p /tmp/digests
@@ -66,16 +88,18 @@ jobs:
           echo "PLATFORM_DIGEST=${PLATFORM//[\/:]/-}" >> "$GITHUB_ENV"
       - name: Upload digest
         uses: actions/upload-artifact@v4
+        if: ${{ !inputs.only-validate }}
         with:
           name: digests-${{ env.TAG_PREFIX_DIGEST }}_${{ env.PLATFORM_DIGEST }}
           path: /tmp/digests/*
           if-no-files-found: error
           retention-days: 1
 
-  merge:
+  publish:
+    name: Publish to Docker Hub
     runs-on: ubuntu-latest
-    needs:
-      - build
+    needs: build
+    if: ${{ !inputs.only-validate }}
     steps:
       - name: Download digests
         uses: actions/download-artifact@v4
@@ -101,6 +125,7 @@ jobs:
       - name: Create manifest list and push
         working-directory: /tmp/digests
         run: |
+          # shellcheck disable=SC2046
           docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
             $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
       - name: Inspect image
diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -4,42 +4,82 @@ on:
   workflow_dispatch:
   schedule:
     - cron: '0 0 1 */1 *'
+  pull_request:
   push:
+    branches:
+      - main
 
-env:
-  REGISTRY_IMAGE: gmazzo/kotlin
+concurrency:
+  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
+  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
-  fetch-versions:
-    name: Fetch Kotlin versions
+  koltin-versions:
+    name: Get latest Kotlin versions
     runs-on: ubuntu-latest
     outputs:
       versions: ${{ steps.fetch.outputs.versions }}
+      latest: ${{ steps.fetch.outputs.latest }}
     steps:
       - name: Fetch Kotlin versions
         id: fetch
         env:
           GH_TOKEN: ${{ github.token }}
+        # Gets the latest 3 major versions, latest patch of them
         run: |
-          echo "versions=$(gh --repo JetBrains/kotlin release list --exclude-drafts --exclude-pre-releases --json tagName,isLatest --jq '[.[] | select(.isLatest) | .tagName | sub("^v"; "")]')" >> "$GITHUB_OUTPUT"
+          VERSIONS=$(gh release list \
+            --repo JetBrains/kotlin \
+            --exclude-drafts \
+            --exclude-pre-releases \
+            --json tagName \
+            --jq '[map(.tagName | sub("^v"; "")) | group_by(. | sub("(?<major>\\d+).*"; .major))[] | sort_by(. | split(".") | map(tonumber))[-1]] | sort_by(. | split(".") | map(-tonumber))[0:3]'
+          )
+          LATEST=$(jq -r '.[0]' <<< "$VERSIONS")
+          echo "::notice::versions=$VERSIONS, latest=$LATEST"
+          echo "versions=$VERSIONS" >> "$GITHUB_OUTPUT"
+          echo "latest=$LATEST" >> "$GITHUB_OUTPUT"
 
   build:
-    name: Build kt${{ matrix.kotlin-version }}-${{ matrix.base-image }}
-    needs: fetch-versions
+    name: Build kt${{ matrix.kotlin-version }}-${{ format(matrix.base-image, matrix.java-version) }}
+    needs: koltin-versions
     uses: ./.github/workflows/build-flavor.yaml
     secrets: inherit
     strategy:
-      fail-fast: false
+      fail-fast: ${{ github.event_name == 'pull_request' }}
       matrix:
-        kotlin-version: ${{ fromJSON(needs.fetch-versions.outputs.versions) }}
+        kotlin-version: ${{ fromJSON(needs.koltin-versions.outputs.versions) }}
+        java-version: [ 11, 17, 21 ]
         base-image:
-          - eclipse-temurin:21
-          - eclipse-temurin:21-alpine
-          - amazoncorretto:21
-          - amazoncorretto:21-alpine
-          - azul/zulu-openjdk:21
-          - azul/zulu-openjdk-alpine:21
+          - eclipse-temurin:{0}
+          - eclipse-temurin:{0}-alpine
+          - amazoncorretto:{0}
+          - amazoncorretto:{0}-alpine
+          - azul/zulu-openjdk:{0}
+          - azul/zulu-openjdk-alpine:{0}
+        include:
+          - kotlin-version: ${{ needs.koltin-versions.outputs.latest }}
+            java-version: 21
+            base-image: eclipse-temurin:{0}-alpine
+            latest: true
+        exclude:
+          - java-version: 11
+            base-image: eclipse-temurin:{0}-alpine
+          - java-version: 17
+            base-image: eclipse-temurin:{0}-alpine
     with:
       kotlin-version: ${{ matrix.kotlin-version }}
-      base-image: ${{ matrix.base-image }}
-      latest: ${{ matrix.base-image == 'eclipse-temurin:21-alpine' }}
+      base-image: ${{ format(matrix.base-image, matrix.java-version) }}
+      latest: ${{ matrix.latest || false }}
+      only-validate: ${{ github.event_name == 'pull_request' }}
+
+  build-completed:
+    name: Build completed
+    needs: build
+    runs-on: ubuntu-latest
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Fail if Build has failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: |
+          echo "::error::Build failed"
+          exit 1
